### ISSUE TITLE
predict.py raises an error

### ISSUE THREAD

**Issue by zeinabsadeghian** [google/neural-tangents#152] opened 2022-05-09 16:52 UTC
Hey guys!
I hope you're doing well:)
So I installed the neural tangent as the instructions in the https://pypi.org/project/neural-tangents/. But when I try to run the tests in the link, this error raises:

RuntimeError: UNKNOWN: C:\Users\USER\anaconda3\lib\site-packages\neural_tangents\_src\predict.py:1163:1: error: 'mhlo.custom_call' op incorrect layout dense<4294967296> : tensor<2xindex> for type 'tensor<1000x1000xf32>', layout must be a permutation of [0, 2)
  C = sp.linalg.cho_factor(A, lower)
^
C:\Users\USER\anaconda3\lib\site-packages\neural_tangents\_src\predict.py:1163:1: note: see current operation: %4 = "mhlo.custom_call"(%1, %2, %3, %0) {api_version = 2 : i32, backend_config = "", call_target_name = "lapack_spotrf", called_computations = [], has_side_effect = false, operand_layouts = [dense<> : tensor<0xindex>, dense<> : tensor<0xindex>, dense<> : tensor<0xindex>, dense<4294967296> : tensor<2xindex>], result_layouts = [dense<4294967296> : tensor<2xindex>, dense<> : tensor<0xindex>]} : (tensor<i32>, tensor<i32>, tensor<i32>, tensor<1000x1000xf32>) -> tuple<tensor<1000x1000xf32>, tensor<i32>>

My tensorflow version is 2.8.0 and python version is 3.9.12. I also installed jaxlib 0.3.7 the CPU version and jax 0.3.10.

Can you tell where exactly the issue is?

**Comment by romanngg** [comment] 2022-05-09 21:37
Based on the numbers in the error message, am I correct that it's raised when running `python examples/infinite_fcn.py`? 

Unfortunately I can't reproduce it on my machine so far, with same versions of python and packages; could you be accidentally running an old version of NT? You could try to run
`pip install --upgrade jax jaxlib neural-tangents` and see if this helps.

Otherwise I haven't seen this kind of low-level error before, and it would help if you could specify it a bit more (which version of Neural Tangents do you use, and which exact command did you run before seeing this error? Are other tests passing, or also failing?).

**Comment by romanngg** [comment] 2022-05-09 21:47
Another avenue to investigate is to try running this python program
```python
from scipy import linalg
# if the above works, next try
# from jax.scipy import linalg
import numpy as np

A = np.random.normal(size=(1000, 1000))
A = A + A.T + np.eye(1000) * 1000

C = linalg.cho_factor(A)
```
to see if the issue is with scipy/lapack/xla.

**Comment by zero0o0o** [comment] 2022-05-10 09:57
> 

linalg from scipy works, However the linag from jax.scipy gives me the same error. 
I also upgraded jax, jaxlib and neural-tangents. Other examples also give me some errors but I think they were all related to linalg again.
For example:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\neural-tangents\examples\function_space.py", line 94, in <module>
    app.run(main)
  File "C:\Users\USER\anaconda3\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\USER\anaconda3\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "C:\Users\USER\neural-tangents\examples\function_space.py", line 85, in main
    fx_train, fx_test = predictor(_TRAIN_TIME, fx_train, fx_test, g_td)
  File "C:\Users\USER\anaconda3\lib\site-packages\neural_tangents\_src\predict.py", line 258, in predict_fn
    return get_predict_fn_finite()(t, fx_train_0, fx_test_0, k_test_train)
  File "C:\Users\USER\anaconda3\lib\site-packages\neural_tangents\_src\predict.py", line 173, in get_predict_fn_finite
    expm1_fn, inv_expm1_fn = _get_fns_in_eigenbasis(
  File "C:\Users\USER\anaconda3\lib\site-packages\neural_tangents\_src\predict.py", line 1131, in _get_fns_in_eigenbasis
    evals, evecs = np.linalg.eigh(k_train_train)
  File "C:\Users\USER\anaconda3\lib\site-packages\jaxlib\lapack.py", line 944, in syevd_mhlo
    ir.DenseIntElementsAttr.get(np.array([0]), type=ir.IndexType.get()),
ValueError: DenseElementsAttr could not be constructed from the given buffer. This may mean that the Python buffer layout does not match that MLIR expected layout and is a bug.

**Comment by zero0o0o** [comment] 2022-05-10 09:58
> > 
> 
> linalg from scipy works, However the linag from jax.scipy gives me the same error. I also upgraded jax, jaxlib and neural-tangents. Other examples also give me some errors but I think they were all related to linalg again. For example:
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "C:\Users\USER\neural-tangents\examples\function_space.py", line 94, in app.run(main) File "C:\Users\USER\anaconda3\lib\site-packages\absl\app.py", line 312, in run _run_main(main, args) File "C:\Users\USER\anaconda3\lib\site-packages\absl\app.py", line 258, in _run_main sys.exit(main(argv)) File "C:\Users\USER\neural-tangents\examples\function_space.py", line 85, in main fx_train, fx_test = predictor(_TRAIN_TIME, fx_train, fx_test, g_td) File "C:\Users\USER\anaconda3\lib\site-packages\neural_tangents_src\predict.py", line 258, in predict_fn return get_predict_fn_finite()(t, fx_train_0, fx_test_0, k_test_train) File "C:\Users\USER\anaconda3\lib\site-packages\neural_tangents_src\predict.py", line 173, in get_predict_fn_finite expm1_fn, inv_expm1_fn = _get_fns_in_eigenbasis( File "C:\Users\USER\anaconda3\lib\site-packages\neural_tangents_src\predict.py", line 1131, in _get_fns_in_eigenbasis evals, evecs = np.linalg.eigh(k_train_train) File "C:\Users\USER\anaconda3\lib\site-packages\jaxlib\lapack.py", line 944, in syevd_mhlo ir.DenseIntElementsAttr.get(np.array([0]), type=ir.IndexType.get()), ValueError: DenseElementsAttr could not be constructed from the given buffer. This may mean that the Python buffer layout does not match that MLIR expected layout and is a bug.

By the way, my neural tangents version is 0.5.0:)

**Comment by romanngg** [comment] 2022-05-10 18:31
Thanks for the update! In this case I recommend submitting this issue to https://github.com/google/jax/issues with a repro from https://github.com/google/neural-tangents/issues/152#issuecomment-1121615513 since it appears to be a jaxlib rather than an NT bug.

**Comment by zero0o0o** [comment] 2022-05-10 18:35
> Thanks for the update! In this case I recommend submitting this issue to https://github.com/google/jax/issues with a repro from [#152 (comment)](https://github.com/google/neural-tangents/issues/152#issuecomment-1121615513) since it appears to be a jaxlib rather than an NT bug.

thanks! I'll do it:)

**Comment by cloudhan** [comment] 2022-05-20 14:39
The root cause is https://github.com/cloudhan/jax-windows-builder/issues/12, and is fixed in jax main branch. But I haven't triggerred a new build.

**Closed** 2023-08-29 16:56 UTC
Labels: bug
